name: build-deploy-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write
  packages: read

jobs:
  deploy-app:
    uses: mahindar5/ng-pwa-app/.github/workflows/common-build-deploy-pages.yml@main
    with:
      base-href: "/my-app/"
      npm-packages: "@mahindar5/common-lib@latest @mahindar5/ng-common-mat-lib@latest"
